atomiks/tippyjs

docs/css/app.css
docs/index.html

Add GitHub button to docs

---

docs/css/app.css
docs/index.html

It simply makes the Popper.js button clickable, just to share some love 💌

docs: Make button clickable

---

README.md
package.json

To publish the library:
1. Register to https://npmjs.org
2. `npm login` and insert your npmjs data
3. `cd` to Tippy.js folder
4. `npm publish` will publish `typpy.js` into the npm registry
From now on `npm install typpy.js` will install your library.
To publish a new version, bump the version number in `package.json` and run `npm publish` again.

update: package.json and README ready for npm

---

docs/index.html
src/js/core/getArrayOfElements.js
src/js/tippy.js
src/js/utils/isObjectLiteral.js
tests/spec/functional.js

@hmtinc
@maxkfranz
Since there were issues with the pull req I implemented the changes into this branch. Can you verify if this is the correct implementation?

refObj implementation

---

src/js/core/followCursorHandler.js

@Whateverinc
Can you verify this fixes the issue?

Fix followCursor distance

---

src/js/core/Tippy.js

ping @TGotwig
Does this fix the issue?
(`npm run build` this branch and grab the dist file)

Follow cursor fix

---

src/js/core/Tippy.js

fix for FF as described in #221

fix #221 do not show on disabled elements in FF

---

src/js/createTippy.js
src/js/utils.js
tests/spec/utils.test.js
tests/visual/index.html

@kfir124
From my testing this seems to fix the issue by replacing `scheduleUpdate` with `update` without performance impact, can you verify?

Fix followCursor jumpiness with fast transition duration

---

src/js/createTippy.js
src/js/defaults.js
src/js/utils.js
tests/spec/utils.test.js

fix setContent() resetting followCursor position

---

index.d.ts
src/js/createTippy.js

Resolves #373 
Check it out @dkulp2?

Add followCursor: 'initial' option

---

src/js/index.js
src/js/utils.js
test/spec/utils.test.js

Fixes https://github.com/atomiks/tippy.js-react/issues/44

Fix virtual element check for JSDOM

---

src/createTippy.ts
src/index.ts
src/utils.ts
tsconfig.json

Simplifies `getArrayOfElements` types and fixes weird issue with `setTimeout`.

Improve utils typings, fix setTimeout

---

index.d.ts
src/types.ts

Import `Placement` from `popper.js` (https://github.com/atomiks/tippyjs/issues/448#issuecomment-471646380).

Use imported Placement

---

demo/index.html
demo/index.js
src/createTippy.ts
src/scss/themes/google.scss
src/scss/themes/light-border.scss
src/scss/themes/light.scss
src/scss/themes/translucent.scss

No need to think about `.tippy-popper` in themes anymore.
Don't know why I didn't think of doing this sooner 🤦‍♂️

Add x-placement to tooltip node

---

demo/extra-props/index.js
src/extra-props/inlinePositioning.ts
test/integration/extra-props.test.js

See https://github.com/atomiks/tippyjs/pull/499#issuecomment-504630197 for details.
Run `npm run dev:extra-props` demo for behavior.
Need to add tests for this.

[WIP] Add `inlinePositioning` as extra-prop

---

src/createTippy.ts
src/popper.ts
src/utils.ts
test/spec/popper.test.js
test/spec/utils.test.js

Fix double whitespace in `theme`

---

src/createTippy.ts
src/index.ts
src/popper.ts
src/utils.ts
src/validation.ts

ESLint deps update no longer warns for these

chore: remove unnecessary return types

---

src/createTippy.ts
src/plugins/inlinePositioning.ts
test/integration/plugins/inlinePositioning.test.js

fix(inlinePositioning): set ReferenceObject in onShow lifecycle hook

---

.travis.yml
index.test-d.ts
package-lock.json
package.json
src/props.ts
tsconfig.json

Added basic type checks for exported API.

test: add type testing

---

src/addons/delegate.ts

fix(delegate): passive event listener warning

---

src/addons/delegate.ts
test/integration/addons/delegate.test.js
test/visual/tests.js

fix(delegate): touch input with click trigger

---

src/addons/createSingleton.ts
src/createTippy.ts
test/integration/addons/createSingleton.test.js

fix(createSingleton): touch and triggerTarget

---

src/createTippy.ts
test/integration/props.test.js

 fix: toggle repeated clicks with inner target element 

---

src/createTippy.ts

Fixes https://github.com/atomiks/tippyjs-react/issues/252

fix: change mounted state after true mount

---

src/createTippy.ts

Fixes https://github.com/atomiks/tippyjs-react/issues/339

fix: check visible state only from hide in handleStyles

---

src/addons/delegate.ts

/cc @amanagr, this should fix the issue
Fix #1005

 fix(delegate): warnings in console with esm 
