- src/js/tippy.js
- webpack.config.js
Now you can pass any Popper.js option to Tippy.js and have it applied properly.
```
new Tippy(el, {
popperOptions: {
modifiers: {
preventOverflow: {
boundariesElement: 'viewport'
}
}
}
})
```
Will apply a custom setting to `preventOverflow` modifier.
> feat: Allow to pass custom Popper.js options

- src/js/tippy.js
- Replaced the use of innerHTML with appendChild when template
content is inserted into a popper.
Why?
- The rest of tippy.js is written to nicely to add/remove the popper from
the DOM while preserving events and element properties.
- By using innerHTML to insert the template it kills any events or
element properties a dev added to the template structure.
- Using appendChild when you have already confirmed it is an HTML
Element object preserves anything the dev adds to the template.
- This allows a dev to create interactive poppers with their own event
handlers and more
> Use appendChild instead of innerHtml for templates

- .travis.yml
- karma.conf.js
Now tests will run on Firefox and Chrome browsers for TravisCI integration
> Add Chrome tests runner for TravisCI

- src/js/core/createTooltips.js
- src/js/core/init.js
- tests/spec/functional.js
Instead of assigning an Element to `appendTo`,
one can now pass a function that evaluates to an Element
The appendTo function is now evaluated during createToolTips/initialization
of the tippy instance, which is good enough for not leaking appendTo
when reinitializing for various DOM changes e.g. in between
multiple `turbolinks:load` transitions.
This also changes the Defaults.appendTo into a function reevaluating the ‘current’ document.body
> Enables passing of function to `appendTo`

- src/js/core/bindEventListeners.js
- src/js/utils/applyTransitionDuration.js
- src/js/utils/closest.js
- src/js/utils/matches.js
Hi there!
Thanks for your wonderful work on tippy, it is saving me a ton of time and effort and I really appreciate it. I am currently using it with preact in a situation where I am server rendering it, meaning it needs to be able to initialize outside the browser environment. There is only one line of code preventing it from doing so, which is the explicit reference to the `Element` global that runs as soon as tippy is imported. I fixed this just by adding a little conditional ensuring that `Element` exists before executing code that depends on it, and that got everything working nicely.
Hopefully this small fix will help out someone else in the future. Thanks again for your great work, and hoping to contribute more here in the future!
> Server Rendering Fix

- src/js/core/getArrayOfElements.js
I ran into a situation where I needed to pass a `NodeList` in directly, rather than letting tippy do the `querySelectorAll`-ing. This PR just makes sure that tippy acceps `NodeList`s without issue.
> Accept a NodeList as input

- docs/index.html
- src/js/core/createTooltips.js
I also ran into a situation where I had multiple elements that needed html tooltips, and each tooltip had to be unique to the element. This was solved by allowing the html to be pulled dynamically through a function, rather than passing in a single element reference 😁
> Dynamic html option

- src/js/core/getArrayOfElements.js
Hi there!
Thanks so much for accepting my previous pull requests! Have been using these features in production and it has gone wonderfully. I noticed when testing in IE that my `NodeList` detection was bugged - unfortunately IE does not have the `constructor.name` property (of course), so if using a `NodeList` input, it would break. This method is much more reliable for detecting whether your input is actually a `NodeList` or not. I tested this in IE and it is working nice and smoothly.
👬
> Better NodeList Detection

- docs/index.html
The word "simply" (like the word "just") is probably intended to convey that the instructions are straightforward, but it can have the unintended side-effect of making the reader feel overwhelmed:
http://bradfrost.com/blog/post/just/
> Remove the word "simply" from documentation

- src/js/core/Tippy.js
FOR #263
This PR provides a function to safely determine the correct transitionend listener to use for the active browser. This fixes an issue with IE11 where onHidden and onShown are not being called.
> Modify how transitionend listener is determined

- .gitignore
- src/js/core/bindEventListeners.js
- src/js/tippy.js
@gargrave. How's this?
```js
// Call this before invoking `tippy()`
tippy.useCapture()
```
> add useCapture static method for global click listener

- src/js/createTippy.js
- src/js/defaults.js
- tests/spec/props.test.js
Offers more comprehensive knowledge about the state of the tooltip.
`onMount()` allows users to access the dimensions of the tooltip, because `onShow()` is called before mounting.
> Add state.isMounted, state.isShown, and props.onMount()

- index.d.ts
- src/js/defaults.js
- src/js/utils.js
- src/scss/tippy.scss
- tests/spec/props.test.js
Resolves #361 
We remove the media query and place this property in `.tippy-popper`
```css
.tippy-popper {
max-width: calc(100% - 10px);
}
```
It prevents the tooltip from ever overflowing if it's too large due to its content, even if style.maxWidth is specified.
Also unlike in V2 you can just use a number without a unit and "px" gets added.
Thoughts? /cc @darrensw777
> Reintroduce maxWidth option

- index.d.ts
Previous value allows only one trigger to be available, you couldn't create string combinations like: `mouseenter focus` etc.
This is a quick fix, the best option is to include props descriptions copied from the docs.
> Typings improvements

- index.d.ts
- src/js/createTippy.js
- src/js/defaults.js
- src/js/utils.js
- tests/spec/defaults.test.js
- tests/spec/utils.test.js
Flat-level alias for `popperOptions.modifiers.preventOverflow.boundariesElement` since it's common
> Add 'boundary' option

- src/js/createTippy.js
- tests/spec/defaults.test.js
@jburghardt going to leave off validation, the docs state the two string values that should be used
Resolves #401
> Avoid setting aria attribute for falsy values

- index.d.ts
- src/js/bindGlobalEventListeners.js
- src/js/createTippy.js
- src/js/deprecated_computeArrowTransform.js
- src/js/utils.js
- tests/spec/utils.test.js
Adding from #398. This PR adds two possible string values to `followCursor`:
- `"initialHorizontal"`
- `"initialVertical"`
If you take a look at Wikipedia's tooltips, they will position themselves near the cursor but only horizontally, which prevents the tooltip from overlapping the text if the cursor entered the anchor link from beneath. `"initial"` does not satisfy that behavior since it behaves on both axes, so we need the ability to specify the axis.
Patches an edge case using `followCursor` with `delay`, where if it was transitioning out but the cursor re-entered the reference, it jumps to the new cursor position, it should wait
Replaces `.indexOf(x) > -1` with a utility function `includes()` due to excessive use now
> Follow cursor additions

- src/js/browser.js
- src/js/css.js
- src/js/popper.js
- src/js/props.js
So had some "fun" debugging why it wasn't working on the great UC Browser through Browserstack 😒 
- `animateFill` effect doesn't work, probably a rendering glitch. The tooltip text is unreadable because white text on white background without the backdrop. Let's disable it if we detect UC Browser
- `transitionend` does not fire because it uses `webkitTransitionEnd` _despite_ supporting unprefixed `transitions` (in the CSS, only transforms use prefixes. Unprefixed transitions have wider support). I can only hope they don't remove `webkitTransitionEnd` 
- Also a check in case the `<head>` doesn't have any nodes in it, we'll use `.appendChild` instead of inserting it before the first node
> Fix UC Browser support

- src/js/createTippy.js
- src/js/popper.js
- test/spec/popper.test.js
Fixes #428 
The CSS transform is hardcoded as `10px`, so we should only use the hardcoded value (10)
> Fix distance option when setting it as default

- src/js/createTippy.js
- test/spec/defaults.test.js
Although disabling flipping is undesirable and less common now with the new flipping behavior, the new flipping behavior broke `flip: false`
> Fix flip option

- index.d.ts
Ref: https://github.com/atomiks/tippyjs/pull/441#issuecomment-471278734
---
You can use custom `Required<T>` type as suggested [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#improved-control-over-mapped-type-modifiers).
```ts
import {Options} from 'tippy.js'
type Props = Required<Options>
```
> Remove WholeProps from index.d.ts

- src/createTippy.ts
- src/props.ts
- test/spec/createTippy.test.js
- test/spec/props.test.js
Ok so this is weird..
I originally used `delay: [0, 20]` as the default because Chrome had this `transitionend` issue where it fires 1 frame too late sometimes.  It's not a memory leak or bug, just an aesthetic thing. 
Using a delay of 20ms fixed the following: When mousing out of the element 1 frame before the tooltip fully showed, it would instantly be unmounted without transitioning out. When mousing in and out of the tooltip quickly it would sometimes unmount instantly rather than smoothly transition out (like interruptible animations should). It's not that big of a deal but kind of bothered me.
However now there's this strange bug where the hide `setTimeout` gets fired _really_ late despite only being 20ms by default. Like 1500ms+ and it leaves the tooltip stuck on the UI for a bit. …
> Fix obscure Chrome setTimeout issue

- src/createTippy.ts
- test/spec/createTippy.test.js
Resolves #423 
- Removes the auto-destroy statement. It causes unexpected behavior and breaks compatibility with shadow DOM. It's not documented anywhere and hides memory leaks so it should be removed. 
- Clarify comment of why we have the `disabled` attribute check
> Change show() checks

- src/constants.ts
- src/createTippy.ts
- src/scss/index.scss
Fixes https://github.com/atomiks/tippy.js-react/issues/67
Changes the "notransition" technique which fixes undesirable transitions when the tippy changes placements on updates.
**Before**: add a `transition: none` CSS class on the tippy once `onShown()` completes
**After**: use some instance flags to check if the previous placement is the same and if the previous update happened while the tippy was visible. If so, disable transitions for a single frame before painting. This is a better way to do it anyway and it fixes the problem linked
(going to be deleting the comments describing the variables after this as they're quite redundant, that's why I didn't add any here)
> Change notransition technique

- src/constants.ts
- src/createTippy.ts
The `x-out-of-boundaries` is the other Popper attribute along with `x-placement` that we should migrate to the tooltip node.
> Add x-out-of-boundaries attribute to tooltip node

- src/createTippy.ts
- src/popper.ts
- test/spec/popper.test.js
(Note: this is a workaround due to Popper's lack of `update` callback in v1, which v2 will have [as a promise])
This previous workaround made `onCreate` / `onUpdate` run at odd times due to being overwritten, this workaround seems to be better.
> Adjust mount callback workaround

- index.d.ts
- src/createTippy.ts
- src/types.ts
As surfaced by #460, `delay` / `wait` don't work for virtual references when calling `.show()` / `.hide()` since they are immediate. Like the internal event handlers, users should be calling the schedule methods instead for virtual references
TODO:
- Should they accept a `duration` argument like `show/hide`?
> Expose schedule{Hide,Show} methods

- index.d.ts
- src/bindGlobalEventListeners.ts
- src/popper.ts
- src/types.ts
- src/utils.ts
- test/spec/popper.test.js
When using a touch device with `hideOnClick: true`, only a single tippy displays when multiple tippys are attached to the reference element
> Fix multiple tippys if using touch

- src/bindGlobalEventListeners.ts
- src/createTippy.ts
- src/ponyfills.ts
- test/browser/index.html
- test/browser/index.js
- `followCursor` currently does not respect `popperOptions.modifiers.preventOverflow.padding` and instead only uses the hardcoded `PADDING` constant, this change makes it respect it
- Resolves #469, prevents the tooltip from moving while the cursor is on top of it. This changes the behavior slightly if the tippy is interactive, since it won't continue to follow the cursor while it's still hiding (unlike it currently does)
Since this change adds some size, found a way to also cut back on the `closest` polyfill by reusing the `closestCallback` function
cc @fractaledmind - I don't think this behavior is exactly what you suggested (to only follow if it's over the parent/popper node) as it only follows if it's over the reference element now.
> followCursor fixes

- index.d.ts
- src/createTippy.ts
- src/props.ts
- src/reference.ts
- src/types.ts
- src/utils.ts
- test/spec/props.test.js
Much needed options for virtual references and for #471
- `triggerTarget` will apply the event listeners (`trigger`) to the the `triggerTarget` node, while the reference is used for positioning instead.
- `onTrigger()` gets invoked upon a real event triggering the tooltip to show, allowing the user to make mutations to the virtual reference element and reposition it based on the event.
- Types fixed to account for `VirtualReference` properly
- Revert #461, this change makes exposing those methods needless as this is the better way to do it
- `reference` and `popper` are both unchanging static variables, so no need to prefix them with `instance.` - saves some bytes to offset this change
`reference` is used for positioning, `triggerTarget` is what the event listeners get applied to:
```js …
```
> Implement `triggerTarget`+ `onTrigger` options

- src/css.ts
See https://github.com/atomiks/tippyjs/issues/482
Decided on using a data attribute instead, after seeing styled-components using `<style data-styled />` in their build.
> Add data attribute to style tag

- index.d.ts
- src/bindGlobalEventListeners.ts
- src/createTippy.ts
- src/group.ts
- src/popper.ts
- src/reference.ts
- src/types.ts
- test/spec/bindGlobalEventListeners.test.js
- test/spec/props.test.js
This removes the global click listener in favor of adding one for each instance. This better supports nesting tooltips (e.g. a popover containing buttons with tooltips on them).
- Needs to be added in both `scheduleShow()` (triggered by event listeners) and `show()` (triggered programmatically)
- Remove `checkHideOnClick` option from HideAllOptions - this was only for internal use due to the global click listener and was not documented for use
- Fix in `group.ts` for supporting this better
> Use per-instance hideOnClick handler

- src/createTippy.ts
- src/scss/index.scss
- src/utils.ts
- test/spec/createTippy.test.js
- test/spec/popper.test.js
- test/spec/props.test.js
- test/spec/utils.test.js
The first commit has the async behavior change when mounting, which if they were testing, could break their tests. But I think this is an implementation detail of tippy, no?
(edited: it does work correctly on IE11)
- Mounting behavior (IE11 scrollbar flicker) (fix #509)
- `followCursor` fixes (respects `boundary` & fix regression where `initial` was not placed correctly on touch devices on first show)
- Ensure `destroy()`'s unmounting of the tippy can never be impeded
- Fix the longstanding interactive scrolling issue
- Fix `path` selector having `pointer-events: auto` (fix #504)
> Backport v5 fixes to v4

- src/createTippy.ts
- src/popper.ts
- test/spec/props.test.js
- Resolves the caveat if the element was near the scrollbar in IE11 (#509) - now there are zero flickers anywhere
- Also restores mounting behavior back to 4.3.1 since the new behavior was unneeded
All that needed to be done was to initially apply styles to the popper before popperInstance is created so it sits in the top left of the page when it gets appended to the body, causing no overflow due to its size. 
Hopefully the mounting behavior is fully fixed now 😅
> Fix additional mounting caveat

- .babelrc
- src/bindGlobalEventListeners.ts
- src/createTippy.ts
- src/props.ts
- src/types.ts
- test/integration/props.test.js
Resolves #522 
Removes `touchHold` in favor of overloading `touch` prop.
And new value: `'longPress'`, which is like `'hold'` but uses a timeout to wait.
> Implement `touch: 'longPress'` and overloaded `touch` prop

- src/css.ts
The PR handles cases of weird layout of <head> tag when styling tags (link, style) aren't children of <head> tag, but they're children of other children of <head> tag. The fix makes firstStyleOrLinkTag variable to ignore such weird cases.
That's the exact case I'm going to handle:
Unfortunately I don't have access to change this code and tippy initialization throws `Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`
> Handle case of weird head tag layout

- src/createTippy.ts
- src/index.ts
- src/plugins/followCursor.ts
- src/popper.ts
- src/utils.ts
- test/unit/utils.test.js
Fixes https://github.com/atomiks/tippy.js-react/issues/121
Tippy has never supported iframes where the script was in a different document (i.e. not CodePen/CodeSandbox iframes), this adds support as discovered by the referenced issue.
- All `instanceof` checks have to be replaced by `{}.toString.call(value)` checks
- All `document` references in instance-based listeners changed to `reference.ownerDocument` (global ones remain)
The reference should never leave its iframe context while the instance is still alive, since it's a static variable reference. Also, the popper should probably be in the same document as the reference too (via `appendTo`, not sure how much this matters though). `triggerTarget` nodes must also be in the same document as the `reference`. I'm sure users of iframes know …
> Fix iframe support

- src/createTippy.ts
- test/integration/createTippy.test.js
Discovered via `createSingleton()` – we were never clearing timeouts on destroy that may have been pending. Though `show()` would not have been called anyway due to the `state.isDestroyed` check.
> Clear timeouts on destroy

- demo/flip/index.js
- src/constants.ts
- src/createTippy.ts
- src/popper.ts
- src/scss/index.scss
- test/integration/props.test.js
- test/unit/popper.test.js
- website/src/components/TippyTransition.js
The prev technique had basically been implemented since v0 and hacks were added progressively to account for edge cases over versions, but it was never the right way to do it.
The new technique is to use padding on the popper element instead  of top/left offsets on tooltip for `distance`. So distance = `popper.style.padding`, instead of `tooltip.style.top` in px. 
This removes the need for an internal custom modifier to compute preventOverflow padding + flip padding, and reduces the complexity of `isCursorOutsideInteractiveBorder`, since the popperRect is accurate.
Updated FLIP demos to account for this (not a public API and super obscure what I was doing with it – so safe to change, & it doesn't really affect anything anyway)
Saves 0.2 kB gzipped
> Change distance technique

- src/addons/createSingleton.ts
- src/addons/delegate.ts
- src/types.ts
- test/integration/addons/createSingleton.test.js
- test/integration/addons/delegate.test.js
Allows ability to pass plugins as 3rd arg to addons, like `tippy()`
Fixes #588 
/cc @KubaJastrz for the types
> Add support for plugins in addons

- src/bindGlobalEventListeners.ts
Access to the properties of `activeElement` occurs before condition, which leads to an error.
For example, error in IE11: `Unable to get property '_tippy' of undefined or null reference`.
I changed the condition, moved access to the `activeElement` properties after condition.
> Fix onWindowBlur activeElement broken condition

- .travis.yml
- use `xenial` linux that doesn't need `before_script` config 
- remove deprecated `sudo: false`
- test on `8` and `lts` node versions, we can switch to v10 once [v8 is end-of-life (2020)](https://nodejs.org/en/about/releases/)
> chore: use modern travis configuration

- package-lock.json
- package.json
- test/integration/addons/createSingleton.test.js
- test/integration/addons/delegate.test.js
- test/integration/createTippy.test.js
- test/integration/plugins/followCursor.test.js
- test/integration/plugins/inlinePositioning.test.js
- test/integration/props.test.js
- test/utils.js
Use `fireEvent` to standardize dispatching events in painless way.
> chore: use `dom-testing-library` for testing events

- package.json
- test/integration/createTippy.test.js
- test/setup.js
I didn't like that I couldn't use `console.log` to debug some values in tests, so I mocked `console.warn` globally.
Not sure if this is the best solution but it works 🤷‍♂
> chore: remove `--silent` flag

- src/addons/createSingleton.ts
- src/addons/delegate.ts
- src/createTippy.ts
- src/utils.ts
- test/integration/createTippy.test.js
- test/unit/utils.test.js
- Addons were `.concat`ing `defaultProps.plugins` unnecessarily since `tippy()` does it.
- Duplicate plugins should be filtered out at `createTippy()` for extra safety.
Most exported plugins when duplicated don't cause issues but make performance worse.
`unique()` could use `[...new Set(plugins)]` which is faster I think, but I'm not sure of how well-supported it is, best to use this one?
> fix: filter out duplicate plugins

- src/addons/createSingleton.ts
- src/addons/delegate.ts
- src/index.ts
- src/plugins/animateFill.ts
- src/plugins/followCursor.ts
- src/plugins/inlinePositioning.ts
- src/plugins/sticky.ts
- src/props.ts
- src/types-internal.ts
- src/types.ts
- website/src/pages/plugins.mdx
- Removes `[key: string]: any` from `Props` (see #631)
- Makes all interfaces that use `Props` become generic (to use `TProps`)
- Add included plugins to `Props` so typechecking is enabled by default even if the plugin isn't passed (there is a DEV warning for this)
> types: refactor interfaces

- src/utils.ts
I think this is caused by microsoft/TypeScript#26378
> types: remove ts-ignore in `normalizeToArray`

- src/types.ts
Export the boundary so that we also use it from Tippy then the Popper itself. Currently, I have something like this...
```js
import Popper from 'popper.js';
class PopoverComponent implements OnChanges, OnDestroy, OnInit {
@Input()
public boundariesElement: Popper.Boundary = 'window';
...
}
```
and would like to replace it with
```js
import {
Boundary as TippyBoundary,
Instance as TippyInstance,
Placement as TippyPlacement,
SingleTarget as TippySingleTarget
} from 'tippy.js';
class PopoverComponent implements OnChanges, OnDestroy, OnInit {
@Input()
public boundariesElement: TippyBoundary = 'window';
...
}
```
Let me know if I missed something so that I can adjust it :)
> Export Boundary as a type

- src/createTippy.ts
- test/integration/createTippy.test.js
This is an implementation proposal for the changes required for the behaviour change proposed at https://github.com/atomiks/tippyjs/issues/649. Currently, the `mouseenter` behaviour always overrides the `click` behaviour. At a high-level, the behaviour change here amounts to respecting the `mouseenter` behaviour only _until_ the reference element is clicked. Then, the existing click behaviour is respected, until the tippy is hidden (e.g. as per `hideOnClick` = `true` || `'toggle'`). Once hidden again, the existing `mouseenter` behaviour is respected once more.
Lower-level description:
- When both mouseenter and click `trigger`s are specified, respect existing mouseenter behaviour until reference element is clicked.
- On click, show the tippy and no longer hide on mouseleave.
- Respect all …
> Modify trigger: 'mouseenter click' behaviour.

- src/createTippy.ts
- test/integration/createTippy.test.js
Addresses bug described at https://github.com/atomiks/tippyjs/issues/668
Also, adds test coverage for interactive tippies, given they involve special/separate event bubbling handling.
> Make mouseenter click behaviour consistent for interactive/non-interactive tippies

- src/createTippy.ts
This resolves the problem with the tooltip not disappearing when focus leaves the element. I was unable to write a test for this as I don't think it's possible to fire an event on one element while having the `target` of that event be a different element, but I could be wrong.
> Hide tippy on focusout from child element to fix #693

- src/createTippy.ts
- src/props.ts
- src/types.ts
- test/integration/__snapshots__/createTippy.test.js.snap
- test/integration/props.test.js
- test/unit/__snapshots__/tippy.test.js.snap
This new props allows to pass a new listener when the user click outside of a shown tippy instance.
Related to https://github.com/atomiks/tippyjs-react/issues/166
> Handle onClickOutside props for tippy instance

- src/plugins/followCursor.ts
- test/integration/plugins/followCursor.test.js
This switches the `followCursor` plugin to use a global mouse listener that stores the mouse coords at all times if the plugin is active for any alive instances. 
This allows the user to call `.show()` at any time and have the tippy position itself at the mouse cursor, which enables some esoteric use cases that bypasses the default `trigger` behavior.
> fix(followCursor): global mouse listener

- website/src/pages/v6/faq.mdx
Removing extra word in the FAQ text
> Fix a typo in FAQ page

- src/dom-utils.ts
- test/unit/dom-utils.test.js
This causes the followCursor plugin to not work when a tooltip is initialized before the template's element is added to the DOM.
> Elements created via a <template> have an ownerDocument with no reference to the body

- src/addons/createSingleton.ts
- src/types.ts
- test/integration/addons/createSingleton.test.js
- test/visual/tests.js
- website/src/pages/v6/addons.mdx
This PR adds the following features/changes to Singleton addon
- Refactored logic from `onTrigger` into `prepareInstance` so that it can be reused in `show`
- Fixed `show` method  for Singletons and introduced 3 overloads
- Specific tippy instance
- Specific reference element
- Index number (relative to references array)
- Show first tippy instance if no argument is passed (this was broken and showing empty tippy at top left)
- Introduced `showNext` and `showPrevious` methods on Singletons
- Both methods will cycle once you reach last/first tippy instance
- `showOnCreate` now works correctly for singletons
- Updated `addons.mdx` docs
Our use-case for these changes: We are trying to create a guide/intro where we need to programatically show a singleton instance, but we realised that show …
> Add show, showNext, showPrevious methods to singletons

- src/createTippy.ts
When tippy content is inside a shadow dom, the `interactive` option is not working.
The reason is 
> Events that happen in shadow DOM have the host element as the target, when caught outside of the component.
the popper is inside the host, so `popper.contains(target)` will always return false.
see https://javascript.info/shadow-dom-events
by using `event.composedPath` instead of the `event.target`, it will get the actual target and fix this bug.
see https://stackoverflow.com/questions/39245488/event-path-is-undefined-running-in-firefox/39245638#39245638
> fix not working interactive option

- src/createTippy.ts
the following fix of https://github.com/atomiks/tippyjs/pull/913
in `onDocumentPress`, the check for `event.target` should all be replaced with `actualTarget`.
Otherwise, if the target is inside shadow root, click the reference won't hide tippy properly, see
> fix wrong target

- src/createTippy.ts
- src/dom-utils.ts
For such a structure where content is a shadow dom:
```
popperContainer
contentElement(shadowDom)
innerElement
innerElement
...
```
If we click on innerElement, the `popperContainer.contains(innerElement)` will return false since it is inside a shadow root. But in tippy's logic, we need to treat popperContainer containing innerElement as true.
So here comes `actualContains` function which check through the shadow dom to maintain the correct logic.
Without this fix, interactive option will not work for dom structure above, see:
> fix contains algorithm for shadow dom

- src/plugins/inlinePositioning.ts
Currently there is a bug when hovering the hiding content, it will be re-triggered but the position is wrong, since the previous cursor index is lost.
This PR fix it by retain the cursor index.
> Fix bug: hovering a hiding content leads to incorrect position.

- src/scss/index.scss
When a tooltip is added to a `<pre>` element (or any elements that has `white-space: pre`), the arrow appears broken.
Example:
(`white-space: pre` was added to the parent `<div>` to trigger the bug)
> fix: reset white-space to its initial value

- website/src/pages/v6/all-props.mdx
docs: add the trigger props detail for hideOnClick
It's the first time I use tippyjs. the doc of hideOnClick is so confuse, I try too many times, but it not work.
finaly, in the source code of the doc, I found it should use with trigger props...
It should add the props detail for fresh user. 
thanks.
> docs: add the trigger props detail for hideOnClick

- README.md
- website/src/pages/v6/getting-started.mdx
I recently published an Ember wrapper for tippyjs: https://github.com/nag5000/ember-tippy. 
Would you mind adding information about it to the readme and website?
> docs: add info about Ember wrapper

- src/props.ts
Plugins are not used when validating props in `setDefaultProps`
```js
import tippy, { followCursor } from 'tippy.js';
tippy.setDefaultProps({
followCursor: true,
plugins: [followCursor],
})
```
```
tippy.js
`followCursor` is not a valid prop. You may have spelled it incorrectly, or if it's a plugin, forgot to pass it in an array as props.plugins. 
All props: https://atomiks.github.io/tippyjs/v6/all-props/
Plugins: https://atomiks.github.io/tippyjs/v6/plugins/
👷‍ This is a development-only message. It will be removed in production.
```
> Pass plugins to `validateProps` in `setDefaultProps`

- src/dom-utils.ts
Very simple solution for the bug I reported on:
[Tippy invokes removeEventListener and addEventListener with an undefined listener #1027
https://github.com/atomiks/tippyjs/issues/1027](https://github.com/atomiks/tippyjs/issues/1027)
Live demonstration available here: https://codepen.io/lazycompiler/pen/rNYxBjQ
> Fix undefined listener invokes (bug #1027)
